### ISSUE TITLE
CalledProcessError: Command '['avconv', '-version']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by FishQian** [pat-coady/trpo#7]
Hi all, 

I am excited about the repo but met this error after running the train.py. Any idea or thoughts on that will be appreciated.
I'm running in 3.16.0-4-amd64, and python 3.5.2
Thanks,

[2017-09-29 14:28:00,861] Starting new video recorder writing to /tmp/Walker2d-v1/Sep-29_21:27:59/openaigym.video.1.29235.video000000.mp4
Traceback (most recent call last):

  File "<ipython-input-4-8a858ba09dd2>", line 1, in <module>
    runfile('/netapp/cnl/home/kqian/anaconda3/envs/mujoco_new/trpo/src/train.py', wdir='/netapp/cnl/home/kqian/anaconda3/envs/mujoco_new/trpo/src')

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/netapp/cnl/home/kqian/anaconda3/envs/mujoco_new/trpo/src/train.py", line 330, in <module>
    main(**vars(args))

  File "/netapp/cnl/home/kqian/anaconda3/envs/mujoco_new/trpo/src/train.py", line 290, in main
    run_policy(env, policy, scaler, logger, episodes=5)

  File "/netapp/cnl/home/kqian/anaconda3/envs/mujoco_new/trpo/src/train.py", line 137, in run_policy
    observes, actions, rewards, unscaled_obs = run_episode(env, policy, scaler)

  File "/netapp/cnl/home/kqian/anaconda3/envs/mujoco_new/trpo/src/train.py", line 90, in run_episode
    obs = env.reset()

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/site-packages/gym/core.py", line 104, in reset
    return self._reset()

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/site-packages/gym/wrappers/monitoring.py", line 41, in _reset
    self._after_reset(observation)

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/site-packages/gym/wrappers/monitoring.py", line 198, in _after_reset
    self._reset_video_recorder()

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/site-packages/gym/wrappers/monitoring.py", line 219, in _reset_video_recorder
    self.video_recorder.capture_frame()

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/site-packages/gym/monitoring/video_recorder.py", line 121, in capture_frame
    self._encode_image_frame(frame)

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/site-packages/gym/monitoring/video_recorder.py", line 168, in _encode_image_frame
    self.metadata['encoder_version'] = self.encoder.version_info

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/site-packages/gym/monitoring/video_recorder.py", line 268, in version_info
    stderr=subprocess.STDOUT)),

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout

  File "/home/kqian/anaconda3/envs/mujoco_new/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)

CalledProcessError: Command '['avconv', '-version']' returned non-zero exit status 1

**Comment by pat-coady** [comment]
@fishchian - Sorry for the delay. Have you been able to run any ai gym environments before? Seems related to displaying episode videos. Are you running on a headless (e.g. no screen) server?

This link shows a very simple ai gym setup, just a few lines of code. You might verify that runs OK on your system first:

https://gym.openai.com/docs/

**Comment by FishQian** [comment]
@pat-coady Hi Pat, Thank you for your response. I'm actually running in a working station and have no problem with displaying videos of Cart-Pole. However, I had problems installing the newest version of mujoco-py (1.5+) and installed 0.5.7 instead. I can also visualize my mujoco model. Look forward to more advice, thanks

**Comment by pat-coady** [comment]
Closing - will be confusing to work on this in 2 different repos. Look here:

https://github.com/garymcintire/mpi_util/issues/2#issuecomment-333671904
